// Core API
export const DEFAULT_HEADERS = {
  'Content-Type': 'application/json',
};

export const DEFAULT_API_BASE_URL = 'https://api.anam.ai';
export const DEFAULT_API_VERSION = '/v1'; // include the leading slash

// Connection closed codes
export const CONNECTION_CLOSED_CODE_NORMAL = 'CONNECTION_CLOSED_CODE_NORMAL';
export const CONNECTION_CLOSED_CODE_MICROPHONE_PERMISSION_DENIED =
  'CONNECTION_CLOSED_CODE_MICROPHONE_PERMISSION_DENIED';
export const CONNECTION_CLOSED_CODE_SIGNALLING_CLIENT_CONNECTION_FAILURE =
  'CONNECTION_CLOSED_CODE_SIGNALLING_CLIENT_CONNECTION_FAILURE';
export const CONNECTION_CLOSED_CODE_WEBRTC_FAILURE =
  'CONNECTION_CLOSED_CODE_WEBRTC_FAILURE';

export const CLIENT_METADATA = {
  client: 'js-sdk',
  version: '0.0.0-development',
};
