name: anam_sdk
description: Flutter SDK for Anam AI - Create interactive AI personas with real-time audio/video streaming
version: 0.1.0
homepage: https://github.com/anam-org/flutter-sdk

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.14.2
  http: ^1.1.0
  web_socket_channel: ^2.4.0
  permission_handler: ^11.0.1
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
