export enum InternalEvent {
  WEB_SOCKET_OPEN = 'WEB_SOCKET_OPEN',
  SIGNAL_MESSAGE_RECEIVED = 'SIGNAL_MESSAGE_RECEIVED',
  WEBRTC_CHAT_MESSAGE_RECEIVED = 'WEBRTC_CHAT_MESSAGE_RECEIVED',
  WEBRTC_CLIENT_TOOL_EVENT_RECEIVED = 'WEBRTC_CLIENT_TOOL_EVENT_RECEIVED',
  WEBRTC_TOOL_CALL_STARTED_EVENT_RECEIVED = 'WEBRTC_TOOL_CALL_STARTED_EVENT_RECEIVED',
  WEBRTC_TOOL_CALL_COMPLETED_EVENT_RECEIVED = 'WEBRTC_TOOL_CALL_COMPLETED_EVENT_RECEIVED',
  WEBRTC_TOOL_CALL_FAILED_EVENT_RECEIVED = 'WEBRTC_TOOL_CALL_FAILED_EVENT_RECEIVED',
  WEBRTC_REASONING_TEXT_MESSAGE_RECEIVED = 'WEBRTC_REASONING_TEXT_MESSAGE_RECEIVED',
}
