export enum InternalEvent {
  WEB_SOCKET_OPEN = 'WEB_SOCKET_OPEN',
  SIGNAL_MESSAGE_RECEIVED = 'SIGNAL_MESSAGE_RECEIVED',
  WEBRTC_CHAT_MESSAGE_RECEIVED = 'WEBRTC_CHAT_MESSAGE_RECEIVED',
  WEBRTC_TOOL_CALL_RECEIVED = 'WEBRTC_TOOL_CALL_RECEIVED',
  WEBRTC_CLIENT_EVENT_RECEIVED = 'WEBRTC_CLIENT_EVENT_RECEIVED',
}
