name: Release

on:
  push:
    branches:
      - main
      - rc
      - alpha

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Create a release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Get New Version
        # only run on main
        if: github.ref == 'refs/heads/main'
        id: version
        run: |
          echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Notify Slack
        # only run on main and if version is not '0.0.0-automated'
        if: github.ref == 'refs/heads/main' && steps.version.outputs.version != '0.0.0-automated'
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "emoji": ":gandalf-party:",
              "link": "https://www.npmjs.com/package/@anam-ai/js-sdk",
              "version": "${{ steps.version.outputs.version }}",
              "appName": "Anam JavaScript SDK"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_RELEASE_NOTIFICATION_WEBHOOK_URL }}
